### ISSUE TITLE
improve ChromeClick function (issues for some pages)

### ISSUE THREAD

**Issue by adegard** [adegard/TagIE.ahk#1]
ChromeClick and ChromeWait function has some problem due to text color for Ctrl +F search (yellow or orange) and because sometime it need to click on 1st or second item or all items of the page...

**Comment by Hassan-Ali123** [comment]
Hi @adegard! I want to discuss something with you. Will you please guide how to design drag and drop  elements which show a generic code when dropped onto the studio's tab control page?

Thanks!
