### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by hekmati1** [adegard/TagIE.ahk#6]
hi im trying to use the tagIE with the simple code 

#include C:\Users\danie\Desktop\instaAutomate-master\TagIE_Editor\TagIE.ahk 
tnav("https://www.google.com/","")

 and get this problem...can you help?

![image](https://user-images.githubusercontent.com/62467652/77225669-d2331780-6b79-11ea-9da2-26c312fecd27.png)

**Comment by adegard** [comment]
Hi hekmati1 ,
please try to .
-Set the firt row of code as: #include TagIE.ahk 
and
-save your file in the same folder of TagIE.ahk
Let me know if you solve the issue.

**Comment by hekmati1** [comment]
hi , thank you for the help but theres still problem.

this is the code and the line i added
[image: image.png]

and now the app wont even open :\

[image: image.png]

‫בתאריך שבת, 21 במרץ 2020 ב-19:18 מאת ‪adegard‬‏ <‪notifications@github.com
‬‏>:‬

**Comment by hekmati1** [comment]
hi, thank you for the help but there's still problem.
 
this is the code and the line I added
image.png
![image](https://user-images.githubusercontent.com/62467652/77234127-c7e23f00-6bb4-11ea-8ca1-307476724d5d.png)


and now the app code won't even open :\

image.png
![image](https://user-images.githubusercontent.com/62467652/77234132-cc0e5c80-6bb4-11ea-84d3-5d0d28f5d9ad.png)

**Comment by hekmati1** [comment]
or maybe you meant in the TagIE file and then that problem appears

![image](https://user-images.githubusercontent.com/62467652/77234334-3673cc80-6bb6-11ea-9001-6b8d67d7dfa2.png)

**Comment by adegard** [comment]
Yes but you need to delete the second include row...
Like this example
```
#include TagIE.ahk
tnav("https://www.google.com","")
tenter("ciao", "q", 0)

Sleep, 1000
pwb.Quit()
ExitApp
Esc::ExitApp
```
